//! # Persona Workflow
//!
//! Interactive persona management for creating and managing personas.
//! Provides guided workflows for persona operations.

use anyhow::Result;
use inquire::{Select, Text};
use std::collections::HashMap;

use crate::cli::interactive::{field_helpers::FieldHelpers, runner::InteractiveRunner, ui::UI};

/// Persona workflow handler
pub struct PersonaWorkflow;

impl PersonaWorkflow {
    /// Interactive persona creation workflow
    ///
    /// Creates a minimal persona with auto-generated ID from name.
    /// The ID is automatically generated by slugifying the name (e.g., "End User" → "end-user").
    /// Users can fill in additional fields later by editing the TOML/SQL record.
    pub fn create_persona() -> Result<()> {
        use crate::core::utils::slugify_for_id;

        UI::show_section_header("Create Persona", "👤")?;

        let name = Text::new("Persona name:")
            .with_help_message("Display name (e.g., 'John Doe', 'Alice Smith')")
            .prompt()?;

        let function = Text::new("Function/Role:")
            .with_help_message("Role or function (e.g., 'System Administrator', 'End User', 'Customer')")
            .prompt()?;

        // Auto-generate ID from name
        let id = slugify_for_id(&name);

        // Show the generated ID to the user
        println!("  Generated ID: {}", id);

        // Create the persona
        let mut runner = InteractiveRunner::new();
        let result = runner.create_persona_interactive(id.clone(), name, function)?;

        UI::show_success(&result)?;

        // Ask if user wants to add custom fields
        let add_fields = Select::new(
            "Would you like to add custom fields now?",
            vec!["No", "Yes"],
        )
        .with_help_message("You can always add/edit fields later")
        .prompt()?;

        if add_fields == "Yes" {
            let persona = runner.get_persona_details(&id)?;
            Self::edit_persona_fields(&mut runner, &id, &persona)?;
            // edit_persona_fields already has a pause, so we're done
        } else {
            UI::pause_for_input()?;
        }

        Ok(())
    }

    /// List all personas
    pub fn list_personas() -> Result<()> {
        UI::show_section_header("Personas", "👥")?;

        let runner = InteractiveRunner::new();
        runner.list_personas()?;

        UI::pause_for_input()?;
        Ok(())
    }

    /// Show persona details
    pub fn show_persona() -> Result<()> {
        UI::show_section_header("Show Persona", "🔍")?;

        let id = Text::new("Persona ID:")
            .with_help_message("Enter the persona ID to view")
            .prompt()?;

        let runner = InteractiveRunner::new();
        runner.show_persona(id)?;

        UI::pause_for_input()?;
        Ok(())
    }

    /// Delete a persona
    pub fn delete_persona() -> Result<()> {
        UI::show_section_header("Delete Persona", "🗑️")?;

        let id = Text::new("Persona ID:")
            .with_help_message("Enter the persona ID to delete")
            .prompt()?;

        // Confirm deletion
        let confirm = Select::new(
            &format!("Are you sure you want to delete persona '{}'?", id),
            vec!["No", "Yes"],
        )
        .prompt()?;

        if confirm == "Yes" {
            let runner = InteractiveRunner::new();
            runner.delete_persona(&id)?;
            UI::show_success("Persona deleted successfully")?;
        } else {
            println!("\n✓ Deletion cancelled.");
        }

        UI::pause_for_input()?;
        Ok(())
    }

    /// Edit an existing persona
    pub fn edit_persona() -> Result<()> {
        UI::show_section_header("Edit Persona", "✏️")?;

        let mut runner = InteractiveRunner::new();

        // Get list of personas
        let persona_ids = runner.get_persona_ids()?;

        if persona_ids.is_empty() {
            UI::show_error("No personas found. Please create a persona first.")?;
            UI::pause_for_input()?;
            return Ok(());
        }

        // Let user select which persona to edit
        let selected_id = Select::new("Select persona to edit:", persona_ids)
            .with_help_message("Choose the persona you want to modify")
            .prompt()?;

        // Load persona details
        let persona = runner.get_persona_details(&selected_id)?;

        // Show edit menu
        loop {
            UI::clear_screen()?;
            UI::show_section_header(&format!("Editing: {}", persona.name), "✏️")?;
            UI::show_info(&format!("ID: {}", persona.id))?;

            let edit_options = vec!["Edit Name", "Edit Custom Fields", "Back to Menu"];

            let choice = Select::new("What would you like to edit?", edit_options).prompt()?;

            match choice {
                "Edit Name" => Self::edit_persona_name(&mut runner, &selected_id, &persona)?,
                "Edit Custom Fields" => {
                    Self::edit_persona_fields(&mut runner, &selected_id, &persona)?
                }
                "Back to Menu" => break,
                _ => {}
            }

            // Reload persona after edits
            let _persona = runner.get_persona_details(&selected_id)?;
        }

        UI::pause_for_input()?;
        Ok(())
    }

    /// Edit persona name
    fn edit_persona_name(
        runner: &mut InteractiveRunner,
        persona_id: &str,
        persona: &crate::core::Persona,
    ) -> Result<()> {
        UI::show_section_header("Edit Persona Name", "📝")?;

        let new_name = Text::new("Name:")
            .with_default(&persona.name)
            .with_help_message("Press Enter to keep current value")
            .prompt()?;

        if new_name == persona.name {
            UI::show_info("No changes made.")?;
            return Ok(());
        }

        let result = runner.update_persona_name(persona_id.to_string(), Some(new_name))?;

        UI::show_success(&result)?;
        UI::pause_for_input()?;
        Ok(())
    }

    /// Edit persona custom fields
    fn edit_persona_fields(
        runner: &mut InteractiveRunner,
        persona_id: &str,
        _persona: &crate::core::Persona,
    ) -> Result<()> {
        UI::show_section_header("Edit Custom Fields", "🎯")?;

        // Get field configuration
        let field_config = runner.get_persona_field_config()?;

        if field_config.is_empty() {
            UI::show_info("No custom fields defined in project configuration.")?;
            UI::pause_for_input()?;
            return Ok(());
        }

        // Get current values
        let current_values = runner.get_persona_field_values(persona_id)?;

        // Prompt for each field
        let mut updated_fields = HashMap::new();

        UI::show_info("Edit fields (smart input based on field type):")?;

        for (field_name, field_def) in &field_config {
            let current_json = current_values.get(field_name);
            let help_msg = field_def
                .description
                .clone()
                .unwrap_or_else(|| format!("{} field", field_def.field_type));

            // Use FieldHelpers to handle different field types automatically
            if let Some(new_value) = FieldHelpers::edit_by_type(
                &field_def.field_type,
                &field_name,
                current_json,
                &help_msg,
            )? {
                updated_fields.insert(field_name.clone(), new_value);
            }
        }

        if updated_fields.is_empty() {
            UI::show_info("No changes made.")?;
            return Ok(());
        }

        let result = runner.update_persona_fields(persona_id.to_string(), updated_fields)?;

        UI::show_success(&result)?;
        UI::pause_for_input()?;
        Ok(())
    }

    /// Interactive persona management menu
    pub fn manage_personas() -> Result<()> {
        UI::clear_screen()?;
        UI::show_section_header("Persona Management", "👤")?;

        loop {
            let options = vec![
                "Create New Persona",
                "Edit Persona",
                "List All Personas",
                "Show Persona Details",
                "Delete Persona",
                "Back to Main Menu",
            ];

            let choice = Select::new("What would you like to do?", options).prompt()?;

            match choice {
                "Create New Persona" => Self::create_persona()?,
                "Edit Persona" => Self::edit_persona()?,
                "List All Personas" => Self::list_personas()?,
                "Show Persona Details" => Self::show_persona()?,
                "Delete Persona" => Self::delete_persona()?,
                "Back to Main Menu" => break,
                _ => {}
            }
        }

        Ok(())
    }
}
